name: Run Tests

on: [push]


jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo chmod +x scripts/run_tests.sh
      - run: |
          sudo scripts/run_tests.sh